/**
 * DEPRECATED: This file is no longer used. ELD logs are now generated by the backend.
 * Do not use this function.
 */
export function generateELDLogs(routeMap, cycleUsed = 0) {
  const logs = [];
  const totalDistance = routeMap.distanceMiles;
  const totalDuration = routeMap.durationHours;

  const MAX_DRIVE_HOURS = 11;
  const MAX_ON_DUTY_HOURS = 14;
  const FUEL_INTERVAL = 150; // miles
  const BREAK_HOURS = 1; // mandatory break every 8 hours driving

  let remainingDistance = totalDistance;
  let remainingHours = totalDuration;
  let day = 1;
  let startTime = 8; // start at 08:00

  while (remainingDistance > 0) {
    // Calculate driving hours today
    let driveHours = Math.min(remainingHours, MAX_DRIVE_HOURS - cycleUsed);

    // Add mandatory break if driving more than 8 hours
    let breakHours = driveHours > 8 ? BREAK_HOURS : 0;

    // On-duty hours include drive + break + 1 hour pickup/dropoff
    const onDutyHours = Math.min(MAX_ON_DUTY_HOURS, driveHours + breakHours + 1);

    // Distance covered today
    const distanceToday = Math.min(remainingDistance, driveHours * (totalDistance / totalDuration));

    // Fuel stops today
    const fuelStops = Math.floor(distanceToday / FUEL_INTERVAL);

    const endTime = startTime + onDutyHours;

    logs.push({
      day: `Day ${day}`,
      start_time: `${Math.floor(startTime)}:00`,
      end_time: `${Math.floor(endTime % 24)}:00`,
      hours_driven: parseFloat(driveHours.toFixed(2)),
      off_duty_hours: parseFloat((MAX_ON_DUTY_HOURS - onDutyHours).toFixed(2)),
      distance_miles: parseFloat(distanceToday.toFixed(2)),
      fuel_stops: fuelStops,
      breaks: breakHours,
    });

    remainingDistance -= distanceToday;
    remainingHours -= driveHours;
    day += 1;
    startTime = 8; // reset start for next day
    cycleUsed = 0; // reset cycle for next day
  }

  return logs;
}
